2022-08-25 09:34:54,333 - sloby.db - ERROR - db connect failed {'host': 'tai.db.elephantsql.com', 'dbname': 'ciqrsftx', 'user': 'ciqrsftx', 'password': 'qhqwls9u9JpK8FZ93amFfNTFEtm2SVD4M', 'should_initialize_database': True}
Traceback (most recent call last):
  File "D:\Sloby\sloby\backend\app\db\api.py", line 47, in __conn_singleton
    conn = connect(
  File "D:\Sloby\sloby\backend\venv\lib\site-packages\psycopg\connection.py", line 578, in connect
    raise ex.with_traceback(None)
psycopg.OperationalError: connection failed: FATAL:  password authentication failed for user "ciqrsftx"
connection to server at "tai.db.elephantsql.com" (18.203.249.221), port 5432 failed: FATAL:  password authentication failed for user "ciqrsftx"
2022-08-25 13:51:05,353 - sloby.db - INFO - Connecting to DB
2022-08-25 13:51:05,665 - sloby.db - INFO - Added user_data table to DB.
2022-08-25 13:51:56,935 - sloby.db - INFO - Connecting to DB
2022-08-25 13:51:57,188 - sloby.db - INFO - Added user_data table to DB.
2022-08-25 13:52:16,039 - sloby.db - INFO - Connecting to DB
2022-08-25 13:52:16,332 - sloby.db - INFO - Added user_data table to DB.
2022-08-25 13:52:16,397 - sloby.db - INFO - Added create_post table to DB.
